"""
added time_stamps

Revision ID: d142d2e48806
Revises: 5f385f14ccd1
Create Date: 2025-01-08 02:16:12.283667
"""

from alembic import op
import sqlalchemy as sa
from datetime import datetime

# revision identifiers, used by Alembic.
revision = 'd142d2e48806'
down_revision = '5f385f14ccd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime, nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime, nullable=True))

    # Update existing rows with a valid datetime
    op.execute("UPDATE contacts SET created_at = '{}', updated_at = '{}'".format(datetime.now(), datetime.now()))

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime, nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime, nullable=True))

    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'contacts', ['contact_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('contact_id')

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###