"""Initial migration.

Revision ID: 512863309e69
Revises: 4267085103d0
Create Date: 2025-01-15 07:50:52.321986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '512863309e69'
down_revision = '4267085103d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email_verified')

    # ### end Alembic commands ###
